# Generated by Django 5.0.6 on 2024-07-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imagge',
            new_name='image',
        ),
    ]
