# Generated by Django 5.0.6 on 2024-07-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0004_rename_imagge_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='imagge',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
